version: "3.9"

services:
  # postgresql:
  #   image: postgres:15-alpine
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_DB: demo_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped

  redis:
    image: redis:7.2-alpine           # Dùng image Redis phiên bản nhẹ
    container_name: redis_cache
    ports:
      - "6379:6379"                  # Mở port 6379 để các service khác truy cập
    volumes:
      - redis-data:/data             # Lưu trữ data để không mất khi container restart
    command: redis-server --appendonly yes  # Bật tính năng AOF để ghi log các lệnh
    restart: unless-stopped 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  # postgres-data:
  redis-data:
  rabbitmq-data:
